import React from 'react'

const LetterAndLine = () => {
    return (
        <div className='p-12'>

            {/* Letter Spacing */}
            <h1 className='tracking-tighter'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione, fugiat?</h1>
            <h1 className='tracking-tight'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione, fugiat?</h1>
            <h1 className='tracking-normal'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione, fugiat?</h1>
            <h1 className='tracking-wide'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione, fugiat?</h1>
            <h1 className='tracking-wider'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione, fugiat?</h1>
            <h1 className='tracking-widest'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione, fugiat?</h1>

            {/* arbitrary value */}
            <h1 className='tracking-[3px]'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione, fugiat?</h1>

            <br /><br />

            {/* Line Height */}
            <p className="leading-3">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Adipisci, iure! Doloremque voluptates quia ut, excepturi cumque expedita! Reprehenderit alias cupiditate unde nihil veritatis, exercitationem non deserunt quaerat adipisci eius nisi harum delectus excepturi suscipit magnam sit cumque commodi dolorum voluptatem molestiae quasi culpa maiores autem! Blanditiis, quam maiores eligendi tempora magni veritatis eveniet voluptas tenetur error atque voluptatibus commodi saepe libero adipisci modi facere possimus animi porro, ut consequatur eius dolorem? Quasi sequi sed cumque consequatur corrupti, animi dolore! Impedit, fugiat at distinctio deserunt eum itaque officia recusandae fugit officiis exercitationem delectus modi dolor placeat laboriosam libero id rem reiciendis.</p> <br /><br />
            <p className="leading-4">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Adipisci, iure! Doloremque voluptates quia ut, excepturi cumque expedita! Reprehenderit alias cupiditate unde nihil veritatis, exercitationem non deserunt quaerat adipisci eius nisi harum delectus excepturi suscipit magnam sit cumque commodi dolorum voluptatem molestiae quasi culpa maiores autem! Blanditiis, quam maiores eligendi tempora magni veritatis eveniet voluptas tenetur error atque voluptatibus commodi saepe libero adipisci modi facere possimus animi porro, ut consequatur eius dolorem? Quasi sequi sed cumque consequatur corrupti, animi dolore! Impedit, fugiat at distinctio deserunt eum itaque officia recusandae fugit officiis exercitationem delectus modi dolor placeat laboriosam libero id rem reiciendis.</p> <br /><br />
            <p className="leading-5">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Adipisci, iure! Doloremque voluptates quia ut, excepturi cumque expedita! Reprehenderit alias cupiditate unde nihil veritatis, exercitationem non deserunt quaerat adipisci eius nisi harum delectus excepturi suscipit magnam sit cumque commodi dolorum voluptatem molestiae quasi culpa maiores autem! Blanditiis, quam maiores eligendi tempora magni veritatis eveniet voluptas tenetur error atque voluptatibus commodi saepe libero adipisci modi facere possimus animi porro, ut consequatur eius dolorem? Quasi sequi sed cumque consequatur corrupti, animi dolore! Impedit, fugiat at distinctio deserunt eum itaque officia recusandae fugit officiis exercitationem delectus modi dolor placeat laboriosam libero id rem reiciendis.</p> <br /><br />
            <p className="leading-6">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Adipisci, iure! Doloremque voluptates quia ut, excepturi cumque expedita! Reprehenderit alias cupiditate unde nihil veritatis, exercitationem non deserunt quaerat adipisci eius nisi harum delectus excepturi suscipit magnam sit cumque commodi dolorum voluptatem molestiae quasi culpa maiores autem! Blanditiis, quam maiores eligendi tempora magni veritatis eveniet voluptas tenetur error atque voluptatibus commodi saepe libero adipisci modi facere possimus animi porro, ut consequatur eius dolorem? Quasi sequi sed cumque consequatur corrupti, animi dolore! Impedit, fugiat at distinctio deserunt eum itaque officia recusandae fugit officiis exercitationem delectus modi dolor placeat laboriosam libero id rem reiciendis.</p> <br /><br />
            <p className="leading-7">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Adipisci, iure! Doloremque voluptates quia ut, excepturi cumque expedita! Reprehenderit alias cupiditate unde nihil veritatis, exercitationem non deserunt quaerat adipisci eius nisi harum delectus excepturi suscipit magnam sit cumque commodi dolorum voluptatem molestiae quasi culpa maiores autem! Blanditiis, quam maiores eligendi tempora magni veritatis eveniet voluptas tenetur error atque voluptatibus commodi saepe libero adipisci modi facere possimus animi porro, ut consequatur eius dolorem? Quasi sequi sed cumque consequatur corrupti, animi dolore! Impedit, fugiat at distinctio deserunt eum itaque officia recusandae fugit officiis exercitationem delectus modi dolor placeat laboriosam libero id rem reiciendis.</p> <br /><br />
            <p className="leading-8">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Adipisci, iure! Doloremque voluptates quia ut, excepturi cumque expedita! Reprehenderit alias cupiditate unde nihil veritatis, exercitationem non deserunt quaerat adipisci eius nisi harum delectus excepturi suscipit magnam sit cumque commodi dolorum voluptatem molestiae quasi culpa maiores autem! Blanditiis, quam maiores eligendi tempora magni veritatis eveniet voluptas tenetur error atque voluptatibus commodi saepe libero adipisci modi facere possimus animi porro, ut consequatur eius dolorem? Quasi sequi sed cumque consequatur corrupti, animi dolore! Impedit, fugiat at distinctio deserunt eum itaque officia recusandae fugit officiis exercitationem delectus modi dolor placeat laboriosam libero id rem reiciendis.</p> <br /><br />
            <p className="leading-9">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Adipisci, iure! Doloremque voluptates quia ut, excepturi cumque expedita! Reprehenderit alias cupiditate unde nihil veritatis, exercitationem non deserunt quaerat adipisci eius nisi harum delectus excepturi suscipit magnam sit cumque commodi dolorum voluptatem molestiae quasi culpa maiores autem! Blanditiis, quam maiores eligendi tempora magni veritatis eveniet voluptas tenetur error atque voluptatibus commodi saepe libero adipisci modi facere possimus animi porro, ut consequatur eius dolorem? Quasi sequi sed cumque consequatur corrupti, animi dolore! Impedit, fugiat at distinctio deserunt eum itaque officia recusandae fugit officiis exercitationem delectus modi dolor placeat laboriosam libero id rem reiciendis.</p> <br /><br />
            <p className="leading-10">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Adipisci, iure! Doloremque voluptates quia ut, excepturi cumque expedita! Reprehenderit alias cupiditate unde nihil veritatis, exercitationem non deserunt quaerat adipisci eius nisi harum delectus excepturi suscipit magnam sit cumque commodi dolorum voluptatem molestiae quasi culpa maiores autem! Blanditiis, quam maiores eligendi tempora magni veritatis eveniet voluptas tenetur error atque voluptatibus commodi saepe libero adipisci modi facere possimus animi porro, ut consequatur eius dolorem? Quasi sequi sed cumque consequatur corrupti, animi dolore! Impedit, fugiat at distinctio deserunt eum itaque officia recusandae fugit officiis exercitationem delectus modi dolor placeat laboriosam libero id rem reiciendis.</p> <br /><br />
            <p className="leading-none">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Adipisci, iure! Doloremque voluptates quia ut, excepturi cumque expedita! Reprehenderit alias cupiditate unde nihil veritatis, exercitationem non deserunt quaerat adipisci eius nisi harum delectus excepturi suscipit magnam sit cumque commodi dolorum voluptatem molestiae quasi culpa maiores autem! Blanditiis, quam maiores eligendi tempora magni veritatis eveniet voluptas tenetur error atque voluptatibus commodi saepe libero adipisci modi facere possimus animi porro, ut consequatur eius dolorem? Quasi sequi sed cumque consequatur corrupti, animi dolore! Impedit, fugiat at distinctio deserunt eum itaque officia recusandae fugit officiis exercitationem delectus modi dolor placeat laboriosam libero id rem reiciendis.</p> <br /><br />
            <p className="leading-tight">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Adipisci, iure! Doloremque voluptates quia ut, excepturi cumque expedita! Reprehenderit alias cupiditate unde nihil veritatis, exercitationem non deserunt quaerat adipisci eius nisi harum delectus excepturi suscipit magnam sit cumque commodi dolorum voluptatem molestiae quasi culpa maiores autem! Blanditiis, quam maiores eligendi tempora magni veritatis eveniet voluptas tenetur error atque voluptatibus commodi saepe libero adipisci modi facere possimus animi porro, ut consequatur eius dolorem? Quasi sequi sed cumque consequatur corrupti, animi dolore! Impedit, fugiat at distinctio deserunt eum itaque officia recusandae fugit officiis exercitationem delectus modi dolor placeat laboriosam libero id rem reiciendis.</p> <br /><br />
            <p className="leading-snug">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Adipisci, iure! Doloremque voluptates quia ut, excepturi cumque expedita! Reprehenderit alias cupiditate unde nihil veritatis, exercitationem non deserunt quaerat adipisci eius nisi harum delectus excepturi suscipit magnam sit cumque commodi dolorum voluptatem molestiae quasi culpa maiores autem! Blanditiis, quam maiores eligendi tempora magni veritatis eveniet voluptas tenetur error atque voluptatibus commodi saepe libero adipisci modi facere possimus animi porro, ut consequatur eius dolorem? Quasi sequi sed cumque consequatur corrupti, animi dolore! Impedit, fugiat at distinctio deserunt eum itaque officia recusandae fugit officiis exercitationem delectus modi dolor placeat laboriosam libero id rem reiciendis.</p> <br /><br />
            <p className="leading-normal">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Adipisci, iure! Doloremque voluptates quia ut, excepturi cumque expedita! Reprehenderit alias cupiditate unde nihil veritatis, exercitationem non deserunt quaerat adipisci eius nisi harum delectus excepturi suscipit magnam sit cumque commodi dolorum voluptatem molestiae quasi culpa maiores autem! Blanditiis, quam maiores eligendi tempora magni veritatis eveniet voluptas tenetur error atque voluptatibus commodi saepe libero adipisci modi facere possimus animi porro, ut consequatur eius dolorem? Quasi sequi sed cumque consequatur corrupti, animi dolore! Impedit, fugiat at distinctio deserunt eum itaque officia recusandae fugit officiis exercitationem delectus modi dolor placeat laboriosam libero id rem reiciendis.</p> <br /><br />
            <p className="leading-relaxed">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Adipisci, iure! Doloremque voluptates quia ut, excepturi cumque expedita! Reprehenderit alias cupiditate unde nihil veritatis, exercitationem non deserunt quaerat adipisci eius nisi harum delectus excepturi suscipit magnam sit cumque commodi dolorum voluptatem molestiae quasi culpa maiores autem! Blanditiis, quam maiores eligendi tempora magni veritatis eveniet voluptas tenetur error atque voluptatibus commodi saepe libero adipisci modi facere possimus animi porro, ut consequatur eius dolorem? Quasi sequi sed cumque consequatur corrupti, animi dolore! Impedit, fugiat at distinctio deserunt eum itaque officia recusandae fugit officiis exercitationem delectus modi dolor placeat laboriosam libero id rem reiciendis.</p> <br /><br />
            <p className="leading-loose">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Adipisci, iure! Doloremque voluptates quia ut, excepturi cumque expedita! Reprehenderit alias cupiditate unde nihil veritatis, exercitationem non deserunt quaerat adipisci eius nisi harum delectus excepturi suscipit magnam sit cumque commodi dolorum voluptatem molestiae quasi culpa maiores autem! Blanditiis, quam maiores eligendi tempora magni veritatis eveniet voluptas tenetur error atque voluptatibus commodi saepe libero adipisci modi facere possimus animi porro, ut consequatur eius dolorem? Quasi sequi sed cumque consequatur corrupti, animi dolore! Impedit, fugiat at distinctio deserunt eum itaque officia recusandae fugit officiis exercitationem delectus modi dolor placeat laboriosam libero id rem reiciendis.</p> <br /><br />


        </div>
    )
}

export default LetterAndLine