import React from 'react'

const Float = () => {
  return (
    <div className='p-12 pb-[50rem]'>

        {/* float-none or default */}
        <p>default or float-none</p>
        <div className='border border-slate-50/50 p-4 mb-20'>
            <img className='w-[200px] h-[200px] rounded-lg object-cover bg-center' src="/images/img1.jpeg" alt="" />
            <p className='text-slate-300'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque magni rem similique in non accusantium ad voluptatum nesciunt dignissimos odio! Quia minus quisquam magnam et, ratione non, architecto suscipit distinctio qui magni minima fuga labore praesentium! Vel earum eligendi iure deleniti id minus natus accusamus soluta veritatis officiis repellendus iste nam mollitia dignissimos praesentium repellat odit numquam aut placeat voluptates, sapiente ipsum, at deserunt facere! Vel aliquid officia, excepturi necessitatibus ea aperiam cumque at neque mollitia quo, tempore sequi doloribus consequuntur et a impedit suscipit doloremque ullam, iusto eaque eveniet aliquam dolorem. Ut tempora, quod vero atque, doloribus quia laboriosam soluta nobis ipsam ad fugit quae. Aliquam quo vero sint neque velit sapiente quibusdam quisquam hic, molestiae nihil suscipit sunt itaque eius et, quis, adipisci est officia ab quae ex blanditiis. Expedita autem excepturi quas dolore quos odio aliquam quia nihil molestiae asperiores quibusdam porro exercitationem possimus consectetur eum, laborum animi libero, ullam dolor minima ducimus. Voluptatum quibusdam, iusto consectetur doloribus reprehenderit voluptate enim, nesciunt est accusamus nihil tenetur quas accusantium! Repellat quod sequi vero vitae, sit, laboriosam neque nemo nesciunt reprehenderit labore quis! Quam deserunt quisquam dignissimos ea beatae veritatis ipsum dolore culpa, vel quod magnam, ducimus minima? Odio.</p>
        </div>

        {/* float-right */}
        <p>float-right</p>
        <div className='border border-slate-50/50 p-4 mb-20'>
            <img className=' float-right              w-[200px] h-[200px] rounded-lg object-cover bg-center' src="/images/img1.jpeg" alt="" />
            <p className='text-slate-300'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque magni rem similique in non accusantium ad voluptatum nesciunt dignissimos odio! Quia minus quisquam magnam et, ratione non, architecto suscipit distinctio qui magni minima fuga labore praesentium! Vel earum eligendi iure deleniti id minus natus accusamus soluta veritatis officiis repellendus iste nam mollitia dignissimos praesentium repellat odit numquam aut placeat voluptates, sapiente ipsum, at deserunt facere! Vel aliquid officia, excepturi necessitatibus ea aperiam cumque at neque mollitia quo, tempore sequi doloribus consequuntur et a impedit suscipit doloremque ullam, iusto eaque eveniet aliquam dolorem. Ut tempora, quod vero atque, doloribus quia laboriosam soluta nobis ipsam ad fugit quae. Aliquam quo vero sint neque velit sapiente quibusdam quisquam hic, molestiae nihil suscipit sunt itaque eius et, quis, adipisci est officia ab quae ex blanditiis. Expedita autem excepturi quas dolore quos odio aliquam quia nihil molestiae asperiores quibusdam porro exercitationem possimus consectetur eum, laborum animi libero, ullam dolor minima ducimus. Voluptatum quibusdam, iusto consectetur doloribus reprehenderit voluptate enim, nesciunt est accusamus nihil tenetur quas accusantium! Repellat quod sequi vero vitae, sit, laboriosam neque nemo nesciunt reprehenderit labore quis! Quam deserunt quisquam dignissimos ea beatae veritatis ipsum dolore culpa, vel quod magnam, ducimus minima? Odio.</p>
        </div>

        {/* float-left */}
        float-left
        <div className='border border-slate-50/50 p-4 mb-20'>
            <img className=' float-left  mr-2          w-[200px] h-[200px] rounded-lg object-cover bg-center' src="/images/img1.jpeg" alt="" />
            <p className='text-slate-300'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque magni rem similique in non accusantium ad voluptatum nesciunt dignissimos odio! Quia minus quisquam magnam et, ratione non, architecto suscipit distinctio qui magni minima fuga labore praesentium! Vel earum eligendi iure deleniti id minus natus accusamus soluta veritatis officiis repellendus iste nam mollitia dignissimos praesentium repellat odit numquam aut placeat voluptates, sapiente ipsum, at deserunt facere! Vel aliquid officia, excepturi necessitatibus ea aperiam cumque at neque mollitia quo, tempore sequi doloribus consequuntur et a impedit suscipit doloremque ullam, iusto eaque eveniet aliquam dolorem. Ut tempora, quod vero atque, doloribus quia laboriosam soluta nobis ipsam ad fugit quae. Aliquam quo vero sint neque velit sapiente quibusdam quisquam hic, molestiae nihil suscipit sunt itaque eius et, quis, adipisci est officia ab quae ex blanditiis. Expedita autem excepturi quas dolore quos odio aliquam quia nihil molestiae asperiores quibusdam porro exercitationem possimus consectetur eum, laborum animi libero, ullam dolor minima ducimus. Voluptatum quibusdam, iusto consectetur doloribus reprehenderit voluptate enim, nesciunt est accusamus nihil tenetur quas accusantium! Repellat quod sequi vero vitae, sit, laboriosam neque nemo nesciunt reprehenderit labore quis! Quam deserunt quisquam dignissimos ea beatae veritatis ipsum dolore culpa, vel quod magnam, ducimus minima? Odio.</p>
        </div>

        {/* clear-left */}
        <p>clear-left</p>
        <div className='border border-slate-50/50 p-4 mb-20'>
              <img className=' float-left  mr-2          w-[200px] h-[200px] rounded-lg object-cover bg-center' src="/images/img1.jpeg" alt="" />
            <p className='clear-left                   text-slate-300'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque magni rem similique in non accusantium ad voluptatum nesciunt dignissimos odio! Quia minus quisquam magnam et, ratione non, architecto suscipit distinctio qui magni minima fuga labore praesentium! Vel earum eligendi iure deleniti id minus natus accusamus soluta veritatis officiis repellendus iste nam mollitia dignissimos praesentium repellat odit numquam aut placeat voluptates, sapiente ipsum, at deserunt facere! Vel aliquid officia, excepturi necessitatibus ea aperiam cumque at neque mollitia quo, tempore sequi doloribus consequuntur et a impedit suscipit doloremque ullam, iusto eaque eveniet aliquam dolorem. Ut tempora, quod vero atque, doloribus quia laboriosam soluta nobis ipsam ad fugit quae. Aliquam quo vero sint neque velit sapiente quibusdam quisquam hic, molestiae nihil suscipit sunt itaque eius et, quis, adipisci est officia ab quae ex blanditiis. Expedita autem excepturi quas dolore quos odio aliquam quia nihil molestiae asperiores quibusdam porro exercitationem possimus consectetur eum, laborum animi libero, ullam dolor minima ducimus. Voluptatum quibusdam, iusto consectetur doloribus reprehenderit voluptate enim, nesciunt est accusamus nihil tenetur quas accusantium! Repellat quod sequi vero vitae, sit, laboriosam neque nemo nesciunt reprehenderit labore quis! Quam deserunt quisquam dignissimos ea beatae veritatis ipsum dolore culpa, vel quod magnam, ducimus minima? Odio.</p>
        </div>

        {/* clear-right */}
        <p>clear-right</p>
        <div className='border border-slate-50/50 p-4 mb-20'>
              <img className=' float-right       mr-2          w-[400px] h-[400px] rounded-lg object-cover bg-center' src="/images/img1.jpeg" alt="" />
            <p className='clear-right                   text-slate-300'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque magni rem similique in non accusantium ad voluptatum nesciunt dignissimos odio! Quia minus quisquam magnam et, ratione non, architecto suscipit distinctio qui magni minima fuga labore praesentium! Vel earum eligendi iure deleniti id minus natus accusamus soluta veritatis officiis repellendus iste nam mollitia dignissimos praesentium repellat odit numquam aut placeat voluptates, sapiente ipsum, at deserunt facere! Vel aliquid officia, excepturi necessitatibus ea aperiam cumque at neque mollitia quo, tempore sequi doloribus consequuntur et a impedit suscipit doloremque ullam, iusto eaque eveniet aliquam dolorem. Ut tempora, quod vero atque, doloribus quia laboriosam soluta nobis ipsam ad fugit quae. Aliquam quo vero sint neque velit sapiente quibusdam quisquam hic, molestiae nihil suscipit sunt itaque eius et, quis, adipisci est officia ab quae ex blanditiis. Expedita autem excepturi quas dolore quos odio aliquam quia nihil molestiae asperiores quibusdam porro exercitationem possimus consectetur eum, laborum animi libero, ullam dolor minima ducimus. Voluptatum quibusdam, iusto consectetur doloribus reprehenderit voluptate enim, nesciunt est accusamus nihil tenetur quas accusantium! Repellat quod sequi vero vitae, sit, laboriosam neque nemo nesciunt reprehenderit labore quis! Quam deserunt quisquam dignissimos ea beatae veritatis ipsum dolore culpa, vel quod magnam, ducimus minima? Odio.</p>
        </div>


        <p>clear-left</p>
        <div className='border border-slate-50/50 p-4 mb-20'>
              <img className=' float-left  mr-2          w-[200px] h-[200px] rounded-lg object-cover bg-center' src="/images/img1.jpeg" alt="" />
              <img className=' float-right  mr-2          w-[400px] h-[400px] rounded-lg object-cover bg-center' src="/images/img1.jpeg" alt="" />
            <p className='clear-left                   text-slate-300'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque magni rem similique in non accusantium ad voluptatum nesciunt dignissimos odio! Quia minus quisquam magnam et, ratione non, architecto suscipit distinctio qui magni minima fuga labore praesentium! Vel earum eligendi iure deleniti id minus natus accusamus soluta veritatis officiis repellendus iste nam mollitia dignissimos praesentium repellat odit numquam aut placeat voluptates, sapiente ipsum, at deserunt facere! Vel aliquid officia, excepturi necessitatibus ea aperiam cumque at neque mollitia quo, tempore sequi doloribus consequuntur et a impedit suscipit doloremque ullam, iusto eaque eveniet aliquam dolorem. Ut tempora, quod vero atque, doloribus quia laboriosam soluta nobis ipsam ad fugit quae. Aliquam quo vero sint neque velit sapiente quibusdam quisquam hic, molestiae nihil suscipit sunt itaque eius et, quis, adipisci est officia ab quae ex blanditiis. Expedita autem excepturi quas dolore quos odio aliquam quia nihil molestiae asperiores quibusdam porro exercitationem possimus consectetur eum, laborum animi libero, ullam dolor minima ducimus. Voluptatum quibusdam, iusto consectetur doloribus reprehenderit voluptate enim, nesciunt est accusamus nihil tenetur quas accusantium! Repellat quod sequi vero vitae, sit, laboriosam neque nemo nesciunt reprehenderit labore quis! Quam deserunt quisquam dignissimos ea beatae veritatis ipsum dolore culpa, vel quod magnam, ducimus minima? Odio.</p>
        </div>

        <p>clear-both</p>
        <div className='border border-slate-50/50 p-4 mb-20'>
              <img className=' float-left  mr-2          w-[200px] h-[200px] rounded-lg object-cover bg-center' src="/images/img1.jpeg" alt="" />
              <img className=' float-right  mr-2          w-[400px] h-[400px] rounded-lg object-cover bg-center' src="/images/img1.jpeg" alt="" />
            <p className='clear-both                   text-slate-300'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque magni rem similique in non accusantium ad voluptatum nesciunt dignissimos odio! Quia minus quisquam magnam et, ratione non, architecto suscipit distinctio qui magni minima fuga labore praesentium! Vel earum eligendi iure deleniti id minus natus accusamus soluta veritatis officiis repellendus iste nam mollitia dignissimos praesentium repellat odit numquam aut placeat voluptates, sapiente ipsum, at deserunt facere! Vel aliquid officia, excepturi necessitatibus ea aperiam cumque at neque mollitia quo, tempore sequi doloribus consequuntur et a impedit suscipit doloremque ullam, iusto eaque eveniet aliquam dolorem. Ut tempora, quod vero atque, doloribus quia laboriosam soluta nobis ipsam ad fugit quae. Aliquam quo vero sint neque velit sapiente quibusdam quisquam hic, molestiae nihil suscipit sunt itaque eius et, quis, adipisci est officia ab quae ex blanditiis. Expedita autem excepturi quas dolore quos odio aliquam quia nihil molestiae asperiores quibusdam porro exercitationem possimus consectetur eum, laborum animi libero, ullam dolor minima ducimus. Voluptatum quibusdam, iusto consectetur doloribus reprehenderit voluptate enim, nesciunt est accusamus nihil tenetur quas accusantium! Repellat quod sequi vero vitae, sit, laboriosam neque nemo nesciunt reprehenderit labore quis! Quam deserunt quisquam dignissimos ea beatae veritatis ipsum dolore culpa, vel quod magnam, ducimus minima? Odio.</p>
        </div>

        <p>clear-none</p>
        <div className='border border-slate-50/50 p-4 mb-20'>
              <img className=' float-left  mr-2          w-[200px] h-[200px] rounded-lg object-cover bg-center' src="/images/img1.jpeg" alt="" />
              <img className=' float-right  mr-2          w-[400px] h-[400px] rounded-lg object-cover bg-center' src="/images/img1.jpeg" alt="" />
            <p className='clear-none                  text-slate-300'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque magni rem similique in non accusantium ad voluptatum nesciunt dignissimos odio! Quia minus quisquam magnam et, ratione non, architecto suscipit distinctio qui magni minima fuga labore praesentium! Vel earum eligendi iure deleniti id minus natus accusamus soluta veritatis officiis repellendus iste nam mollitia dignissimos praesentium repellat odit numquam aut placeat voluptates, sapiente ipsum, at deserunt facere! Vel aliquid officia, excepturi necessitatibus ea aperiam cumque at neque mollitia quo, tempore sequi doloribus consequuntur et a impedit suscipit doloremque ullam, iusto eaque eveniet aliquam dolorem. Ut tempora, quod vero atque, doloribus quia laboriosam soluta nobis ipsam ad fugit quae. Aliquam quo vero sint neque velit sapiente quibusdam quisquam hic, molestiae nihil suscipit sunt itaque eius et, quis, adipisci est officia ab quae ex blanditiis. Expedita autem excepturi quas dolore quos odio aliquam quia nihil molestiae asperiores quibusdam porro exercitationem possimus consectetur eum, laborum animi libero, ullam dolor minima ducimus. Voluptatum quibusdam, iusto consectetur doloribus reprehenderit voluptate enim, nesciunt est accusamus nihil tenetur quas accusantium! Repellat quod sequi vero vitae, sit, laboriosam neque nemo nesciunt reprehenderit labore quis! Quam deserunt quisquam dignissimos ea beatae veritatis ipsum dolore culpa, vel quod magnam, ducimus minima? Odio.</p>
        </div>






    </div>
  )
}

export default Float