import React from 'react'

const Margin = () => {
    return (
        <div className=' pb-[50rem]'>

            <div className='m-8 p-8 bg-slate-600 text-slate-400'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed delectus commodi iusto nesciunt error maxime temporibus sapiente ad quisquam ex natus reprehenderit ab dolores aperiam vel nihil eum sint esse at cumque ut, et blanditiis nulla alias. Doloremque odio illum et quidem quasi soluta itaque voluptatem provident corrupti suscipit ratione quaerat atque nostrum minus, natus at dignissimos veniam repellendus eos dolorum hic? Ut voluptatum laborum incidunt explicabo, repellendus expedita dolores ab minima nisi. Repudiandae quisquam eveniet dignissimos numquam nemo ab commodi, quo amet facilis libero totam in? Praesentium perspiciatis placeat porro obcaecati nisi dignissimos illum tenetur ad fugiat sunt voluptatum, recusandae molestias, unde eaque ex eligendi totam mollitia temporibus corrupti. Necessitatibus inventore quibusdam, nemo porro fuga corporis minima cumque tenetur odio reiciendis esse aliquid at doloribus consectetur in dignissimos iure possimus, ex ipsa illum aperiam voluptates laboriosam velit? Sed quod repudiandae provident autem cupiditate consequatur beatae quae sint totam dicta.</div>

            <div className='mx-8 p-8 bg-slate-600 text-slate-400'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed delectus commodi iusto nesciunt error maxime temporibus sapiente ad quisquam ex natus reprehenderit ab dolores aperiam vel nihil eum sint esse at cumque ut, et blanditiis nulla alias. Doloremque odio illum et quidem quasi soluta itaque voluptatem provident corrupti suscipit ratione quaerat atque nostrum minus, natus at dignissimos veniam repellendus eos dolorum hic? Ut voluptatum laborum incidunt explicabo, repellendus expedita dolores ab minima nisi. Repudiandae quisquam eveniet dignissimos numquam nemo ab commodi, quo amet facilis libero totam in? Praesentium perspiciatis placeat porro obcaecati nisi dignissimos illum tenetur ad fugiat sunt voluptatum, recusandae molestias, unde eaque ex eligendi totam mollitia temporibus corrupti. Necessitatibus inventore quibusdam, nemo porro fuga corporis minima cumque tenetur odio reiciendis esse aliquid at doloribus consectetur in dignissimos iure possimus, ex ipsa illum aperiam voluptates laboriosam velit? Sed quod repudiandae provident autem cupiditate consequatur beatae quae sint totam dicta.</div>
            <div className='my-8 p-8 bg-slate-600 text-slate-400'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed delectus commodi iusto nesciunt error maxime temporibus sapiente ad quisquam ex natus reprehenderit ab dolores aperiam vel nihil eum sint esse at cumque ut, et blanditiis nulla alias. Doloremque odio illum et quidem quasi soluta itaque voluptatem provident corrupti suscipit ratione quaerat atque nostrum minus, natus at dignissimos veniam repellendus eos dolorum hic? Ut voluptatum laborum incidunt explicabo, repellendus expedita dolores ab minima nisi. Repudiandae quisquam eveniet dignissimos numquam nemo ab commodi, quo amet facilis libero totam in? Praesentium perspiciatis placeat porro obcaecati nisi dignissimos illum tenetur ad fugiat sunt voluptatum, recusandae molestias, unde eaque ex eligendi totam mollitia temporibus corrupti. Necessitatibus inventore quibusdam, nemo porro fuga corporis minima cumque tenetur odio reiciendis esse aliquid at doloribus consectetur in dignissimos iure possimus, ex ipsa illum aperiam voluptates laboriosam velit? Sed quod repudiandae provident autem cupiditate consequatur beatae quae sint totam dicta.</div>

            <div className='mr-8 p-8 bg-slate-600 text-slate-400'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed delectus commodi iusto nesciunt error maxime temporibus sapiente ad quisquam ex natus reprehenderit ab dolores aperiam vel nihil eum sint esse at cumque ut, et blanditiis nulla alias. Doloremque odio illum et quidem quasi soluta itaque voluptatem provident corrupti suscipit ratione quaerat atque nostrum minus, natus at dignissimos veniam repellendus eos dolorum hic? Ut voluptatum laborum incidunt explicabo, repellendus expedita dolores ab minima nisi. Repudiandae quisquam eveniet dignissimos numquam nemo ab commodi, quo amet facilis libero totam in? Praesentium perspiciatis placeat porro obcaecati nisi dignissimos illum tenetur ad fugiat sunt voluptatum, recusandae molestias, unde eaque ex eligendi totam mollitia temporibus corrupti. Necessitatibus inventore quibusdam, nemo porro fuga corporis minima cumque tenetur odio reiciendis esse aliquid at doloribus consectetur in dignissimos iure possimus, ex ipsa illum aperiam voluptates laboriosam velit? Sed quod repudiandae provident autem cupiditate consequatur beatae quae sint totam dicta.</div>
            <div className='mt-8 p-8 bg-slate-600 text-slate-400'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed delectus commodi iusto nesciunt error maxime temporibus sapiente ad quisquam ex natus reprehenderit ab dolores aperiam vel nihil eum sint esse at cumque ut, et blanditiis nulla alias. Doloremque odio illum et quidem quasi soluta itaque voluptatem provident corrupti suscipit ratione quaerat atque nostrum minus, natus at dignissimos veniam repellendus eos dolorum hic? Ut voluptatum laborum incidunt explicabo, repellendus expedita dolores ab minima nisi. Repudiandae quisquam eveniet dignissimos numquam nemo ab commodi, quo amet facilis libero totam in? Praesentium perspiciatis placeat porro obcaecati nisi dignissimos illum tenetur ad fugiat sunt voluptatum, recusandae molestias, unde eaque ex eligendi totam mollitia temporibus corrupti. Necessitatibus inventore quibusdam, nemo porro fuga corporis minima cumque tenetur odio reiciendis esse aliquid at doloribus consectetur in dignissimos iure possimus, ex ipsa illum aperiam voluptates laboriosam velit? Sed quod repudiandae provident autem cupiditate consequatur beatae quae sint totam dicta.</div>
            <div className='mb-8 p-8 bg-slate-600 text-slate-400'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed delectus commodi iusto nesciunt error maxime temporibus sapiente ad quisquam ex natus reprehenderit ab dolores aperiam vel nihil eum sint esse at cumque ut, et blanditiis nulla alias. Doloremque odio illum et quidem quasi soluta itaque voluptatem provident corrupti suscipit ratione quaerat atque nostrum minus, natus at dignissimos veniam repellendus eos dolorum hic? Ut voluptatum laborum incidunt explicabo, repellendus expedita dolores ab minima nisi. Repudiandae quisquam eveniet dignissimos numquam nemo ab commodi, quo amet facilis libero totam in? Praesentium perspiciatis placeat porro obcaecati nisi dignissimos illum tenetur ad fugiat sunt voluptatum, recusandae molestias, unde eaque ex eligendi totam mollitia temporibus corrupti. Necessitatibus inventore quibusdam, nemo porro fuga corporis minima cumque tenetur odio reiciendis esse aliquid at doloribus consectetur in dignissimos iure possimus, ex ipsa illum aperiam voluptates laboriosam velit? Sed quod repudiandae provident autem cupiditate consequatur beatae quae sint totam dicta.</div>
            <div className='ml-8 p-8 bg-slate-600 text-slate-400'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed delectus commodi iusto nesciunt error maxime temporibus sapiente ad quisquam ex natus reprehenderit ab dolores aperiam vel nihil eum sint esse at cumque ut, et blanditiis nulla alias. Doloremque odio illum et quidem quasi soluta itaque voluptatem provident corrupti suscipit ratione quaerat atque nostrum minus, natus at dignissimos veniam repellendus eos dolorum hic? Ut voluptatum laborum incidunt explicabo, repellendus expedita dolores ab minima nisi. Repudiandae quisquam eveniet dignissimos numquam nemo ab commodi, quo amet facilis libero totam in? Praesentium perspiciatis placeat porro obcaecati nisi dignissimos illum tenetur ad fugiat sunt voluptatum, recusandae molestias, unde eaque ex eligendi totam mollitia temporibus corrupti. Necessitatibus inventore quibusdam, nemo porro fuga corporis minima cumque tenetur odio reiciendis esse aliquid at doloribus consectetur in dignissimos iure possimus, ex ipsa illum aperiam voluptates laboriosam velit? Sed quod repudiandae provident autem cupiditate consequatur beatae quae sint totam dicta.</div>

        </div>
    )
}

export default Margin